#!/bin/bash
#
# DDT <command> Docker Dialog Toolkit for docker containers
#
# Simple commands to manage containers using dialog boxex
# In order to work properly this file any function defined
# in file 'dtk' (Docker ToolKit), have to be sourced before
#
# Author: Riccardo Bruno <riccardo.bruno@ct.infn.it>

DDT_TMPFILES=()
_cleanup() {
  #echo "Cleaning up ..."
  #echo "files: "${DDT_TMPFILES[@]}
  DDT_RMFILES=(${DDT_TMPFILES[@]})
  for f in ${DDT_TMPFILES[@]}; do
    #printf "Cleaning temporary file: $f ... "
    rm -f $f && DDT_RMFILES=(${DDT_RMFILES[@]/$f}) #&& echo "ok" || echo "failed"
  done
  DDT_TMPFILES=(${DDT_RMFILES[@]})
}
trap _cleanup EXIT

_tmp() {
  RES=$(mktemp)
  [ "$RES" != "" ] && DDT_TMPFILES+=("$RES")
}

_chk() {
  DVER=$(dialog --version 2>/dev/null)
  [ -z "$DVER" ] &&\
      echo "Please install dialog package in your system" &&\
      RES=1 || RES=0
}

_confirm() {
  CNT_NAME=$1
  dialog --title "Delete container" \
	 --keep-tite \
         --yesno "Are you sure you want to delete container $CNT_NAME?" 7 60 2>$SEL
  RES=$?
  return $RES
}

#
# Help
#

ddt_help() {
cat <<EOF
Available ddt_<commands> divided by topics:

Containers
 'ddt_sel' Select a docker container from the list of all available containers. This command can be used in conjunction with 'dtk' defined functions
 'ddt_con' Open a bash terminal against the selected docker container
 'ddt_restart' Restart  a selected container
 'ddt_stop' Stop the selected container
 'ddt_start' Start the selected container
 'ddt_start' Show logs of the selected container
 'ddt_rm' Remove the selected container, (it asks for confirmation)
 'ddt_net' Select one of the defined docker networks (ddt_net* commands are still under development)
 'ddt_inspect' Inspect the selected container

Images
 'ddt_imgsel' Select a docker image form the list of available images. This command can be used in conjunction with dtk defined functions
 'ddt_imgcon' Connect to the selected image. It opens a /bin/bash console prompting user to destroy container upon exit
 'ddt_imgrun' Execute the selected image as daemon
EOF
}

#
# Containers
#

ddt_sel() {
  [ "$1" == "" ] && FN="" || FN=": $1"
  _chk; [ $RES -ne 0 ] && return 1
  _tmp; TMP=$RES
  _tmp; SEL=$RES
  sudo docker ps --all --format "{{.ID}} {{.Names}}" > $TMP
  dialog --title "Container selection$FN" \
	 --keep-tite\
	 --menu 'Please select a container from the list' 18 70 15 $(cat $TMP) 2>$SEL
  CNT=$(cat $SEL)
  _cleanup
}
export -f ddt_sel

ddt_con() {
  ddt_sel "Connect" && dattach
}

ddt_restart() {
  ddt_sel "Restart" && [ "$CNT" != "" ] && drestart
}

ddt_stop() {
  ddt_sel "Stop" && [ "$CNT" != "" ] && dstop
}

ddt_start() {
  ddt_sel "Start" && [ "$CNT" != "" ] && dstart
}

ddt_logs() {
  ddt_sel "Logs" && [ "$CNT" != "" ] && dlogs
}

ddt_rm() {
  [ "$1" != "" ] && CNT=$1 || ddt_sel "Delete" 
  [ "$CNT" != "" ] && _confirm $CNT && drm || echo "Operation cancelled"
}

ddt_inspect() {
  ddt_sel "Inspect" && [ "$CNT" != "" ] && dinspect || echo "Operation cancelled"
}

ddt_net() {
 _chk; [ $RES -ne 0 ] && return 1
 _tmp; TMP=$RES
 _tmp; SEL=$RES
 sudo docker network ls --format "{{.ID}} {{.Name}}" > $TMP
 dialog --keep-tite\
         --menu 'Please select a network from the list' 18 70 15 $(cat $TMP) 2>$SEL
 CNW=$(cat $SEL)
 [ "$CNW" != "" ] && sudo docker network inspect $CNW | jq '.'
  _cleanup
}

#
# Images
#

ddt_imgsel() {
  [ "$1" == "" ] && FN="" || FN=": $1"
  _chk; [ $RES -ne 0 ] && return 1
  _tmp; TMP=$RES
  _tmp; SEL=$RES
  sudo docker image ls --format " \"{{.ID}}\" \"{{.Repository}}:{{.Tag}} ({{.CreatedSince}})\"" > $TMP
  CMD="dialog --title \"Image selection$FN\" --keep-tite --menu 'Please select an image from the list' 18 70 15 $(cat $TMP) 2>$SEL"
  eval $CMD
  IMG=$(cat $SEL)
  _cleanup
}
export -f ddt_imgsel

ddt_imgcon() {
  ddt_imgsel "Connect" && [ "$IMG" != "" ] && dimgcon && ddt_rm $(cat .$IMG) || echo "Operation cancelled"
}
export -f ddt_imgcon

ddt_imgrun() {
 [ "$1" != "" ] && CNM=$1 || CNM=""
 ddt_imgsel "Run" && [ "$IMG" != "" ] && dimgrun || echo "Operation cancelled"
}
export -f ddt_imgrun
 
